### ISSUE TITLE
Unfaithful Answers

### ISSUE THREAD

**Issue by dianetc** [awslabs/rag-qa-arena#4]
Thank you for this work!

We get faithful answers from human annotators (along  with corresponding citations for each answer). **Where do the unfaithful answers come from? How are they generated?** For example, I see quite a few in the `technology_references.json` file from the google drive 

Also, in the [citations version ](https://github.com/awslabs/rag-qa-arena/blob/main/data/annotations_technology_with_citation.jsonl) of the technology data there seems to only be 12 entries for unfaithful answer but the google drive (uncited) version has one for almost each question. Why the discrepancy?

**Comment by rujunhan** [comment]
Hello, unfaithful answers are also annotated by human annotators. We instructed them to insert an error in the original faithful answer. 

We eventually decided not to use the unfaithful answer in our paper, and this repo is only for reproducing the results in the paper. Feel free to leverage the unfaithful answers if it is any helpful to your work.
